apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: restaurant-api
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce  # Le volume peut être monté en lecture-écriture par un seul nœud
  resources:
    requests:
      storage: 5Gi   # 5 Go de stockage persistant
  # storageClassName: standard  # Décommentez si besoin (dépend du cluster)
